### ISSUE TITLE
How to skip reporting certain status codes as errors

### ISSUE THREAD

**Issue by luads** [newrelic/newrelic-node-apollo-server-plugin#142]
## Is your feature request related to a problem? Please describe.
Our applications have been reporting any 401, 403, 404 errors to New Relic. This is creating unwanted noise as those shouldn't be reported and just returned back to the user.

I couldn't find a way of configuring Apollo so that those errors wouldn't be picked up by the NR plugin. No luck using NestJS's exception filters either. 

I'm not sure if the plugin is the right place for that, so I'm not opening a PR until I get some feedback.

## Feature Description
The plugin would be able to receive an array of status codes or exception types to be ignored, example:

```typescript
    GraphQLModule.forRoot({
      plugins: [
        newRelicApolloPlugin.default({
          ignoredStatusCodes: [
            HttpStatus.BAD_REQUEST,
            HttpStatus.UNAUTHORIZED,
            HttpStatus.FORBIDDEN,
            HttpStatus.NOT_FOUND,
          ],
        }),
      ],
      sortSchema: true,
    }),
```

## Describe Alternatives
- The error could be somehow skipped on the framework level
- Maybe there's another way to throw these errors on the application?

## Additional context
I've put together a proof of concept of how it'd look like if this was implemented in the plugin: https://github.com/newrelic/newrelic-node-apollo-server-plugin/compare/main...luads:ignore-specific-status-codes?expand=1

**Comment by lewisgj** [comment]
I wanted to raise a similar issue I've been having - happy to move it to a separate one if you don't think it's related.

It is convention in GraphQL implementations like Apollo that we throw exceptions to return errors back to the client - such as Apollo's UserInputError. We use these a bit like we'd use a 400 or a 422 status code in a REST API - the request passes basic validation but it doesn't make sense logically/semantically. 

We'd love to be able to mark those kinds of errors (or perhaps a custom error) as "expected" in New Relic terms - or ignore them completely as the original issue raiser suggested.

I don't think ignoring _status codes_ is what I'd personally need - since there isn't always a backend that is throwing them in our case, but maybe this would also be suitable for that.

**Comment by luads** [comment]
It's been one year since I posted this. I'm not working on this problem anymore, so I won't be able to provide more details. Feel free to close the issue if you don't deem it relevant.

**Comment by jawang35** [comment]
Any chance we can reopen this? We're having the same problem. There's no way to ignore certain error status codes because Apollo Server always returns a `200`.

**Comment by jawang35** [comment]
Was able to solve this by using `error_collector.ignore_classes`.
