### ISSUE TITLE
apollo-server-plugin compatibility with Fastify V2

### ISSUE THREAD

**Issue by prateekm21** [newrelic/newrelic-node-apollo-server-plugin#68]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

1) Not able to start server for integration test environment without providing real key and able to connect to collector
2) Is this package compatible with Fastify v2 

## Expected Behavior

We should be able to use this library and run server for integration test without requirement to provide NewRelic key and collector connection

## Steps to Reproduce

https://discuss.newrelic.com/t/node-requiring-key-in-test-env-apollo-server-plugin/137364
Here is the code snippet that I am using with NestJS framework

## Your Environment

- Node v12
- NestJS framework
- apollo-server-fastify: "^2.19.2"
- @newrelic/apollo-server-plugin: "^0.1.2"

**Comment by michaelgoin** [comment]
Hi @prateekm21 ,

For 1, are you saying your apollo server didn't work anymore when using our plugin w/o a license key or that our plugin instrumentation did not work (aka the agent did not connect)? If the latter, that is by design. Without a license key, we have nowhere to send the data so the agent disconnects as not to add unnecessary overhead. There is a serverless flag you could use to see some data spit out to the command-line but it won't be of much value. If we are breaking your server implementation w/o license key, it is likely apollo-server-fastify or whatever you are using for `GraphQLModule.forRootAsync` handling plugin returns differently than the apollo-server* plugins made by Apollo. We might be able to protect against it but we'd prioritize making sure the other libraries work.

For 2, we have not tested/have not attempted to add support for apollo-server-fastify. Known supported modules are listed on the readme here: https://github.com/newrelic/newrelic-node-apollo-server-plugin#usage.

**Comment by michaelgoin** [comment]
@prateekm21 sorry! got my wires crossed. I was thinking of a different framework and should have stopped to verify. We do have some tests / standard-case verification around `apollo-server-fastify`: https://github.com/newrelic/newrelic-node-apollo-server-plugin/tree/main/tests/versioned/apollo-server-fastify.

That should work, although there could be some unsupported edge cases. That being said, your code snippet doesn't look like anything we'd tested: `GraphQLModule.forRootAsync`. Doing a quick search, it appears that may come from `@nestjs/graphql` which we have not tested or attempted to support as of yet.
